services:
  demo-kuma:
    image: ghcr.io/stonith404/pocket-id-demo
    restart: unless-stopped
    ports:
      - 3003:80
    command: tsx watch --inspect ./src/server.ts
    volumes:
      - ./:/app
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - NODE_ENV=development

      # Demo Website Name
      - WEBSITE_NAME=Pocket ID

      # Stack Prefix (Should a special prefix, because demo-kuma will manage (start/shutdown) all stacks with this)
      - STACK_PREFIX=pocket-id-demo

      # Specify the service name of the stack
      - STACK_MAIN_SERVICE_NAME=main

      # Specify the port of the service
      - STACK_MAIN_SERVICE_PORT=80

      # The entry path of the demo
      # Should be start with /
      - STACK_MAIN_SERVICE_ENTRY_PATH=/login/setup

      # Session Time (Seconds)
      - SESSION_TIME=600

      # If the stack has not started in time, it will be considered as failed (Seconds)
      - START_TIMEOUT=10

      # Show Entry
      # If true, the entry will be shown in the demo page and the user has to click "Start Demo" to start the demo
      # true / false
      - SHOW_ENTRY=true

      # Install URL for the "Install now" button
      - INSTALL_URL=https://github.com/louislam/uptime-kuma

      # Docker Network Name
      # The demo instance must be in the same network as the demo-kuma
      - DOCKER_NETWORK_NAME=pocket-id-demo_default

      # HTTPS Enabled
      # true / false
      - HTTPS_ENABLED=false

      # Max Sessions
      # The maximum number of sessions that can be active at the same time
      - MAX_SESSSIONS=30

      # If a proxy is in front
      - TRUST_PROXY=true

      # Rate Limit
      - RATE_LIMIT_REFILL_RATE=900
      - RATE_LIMIT_TOKEN_CAPACITY=5
