services:
  # Main Service that you want to create a demo
  main:
    image: stonith404/pocket-id
    restart: no

    # The network name should be the same as the one in compose.yaml, so that demo-kuma can find it and access it
    # You should keep this
    networks:
      - pocket-id-demo_default
    environment:
      - PUBLIC_APP_URL=${PUBLIC_APP_URL}

networks:
  # The network name should be the same as the one in compose.yaml, so that demo-kuma can find it and access it
  # You should keep this
  pocket-id-demo_default:
    external: true
